/**
 * Report Generator
 * Creates beautiful markdown reports from scraped data
 */

import { config } from '../config.js';

export class ReportGenerator {
  constructor() {
    this.date = new Date().toISOString().split('T')[0];
    this.timestamp = new Date().toLocaleString('en-US', {
      timeZone: 'UTC',
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  }

  /**
   * Generate complete daily report
   */
  generate(data) {
    const sections = [
      this.generateHeader(),
      this.generateExecutiveSummary(data),
      this.generateTrendingTopics(data),
      this.generateCompetitorActivity(data),
      this.generateOpportunityAlerts(data),
      this.generateActionItems(data),
      this.generateFooter()
    ];

    return sections.join('\n\n---\n\n');
  }

  generateHeader() {
    return `# 📊 Daily Business Intelligence Report

**Date:** ${this.timestamp} UTC  
**Generated by:** RITA's Intel Engine 🦋  
**Businesses:** Asobo Creations + Peptide Ventures

> 💡 *This report is auto-generated while you sleep. Review when convenient.*
`;
  }

  generateExecutiveSummary(data) {
    const { pinterest, etsy } = data;
    
    const trendCount = pinterest?.flatMap(p => p.trends).length || 0;
    const productCount = etsy?.products?.length || 0;
    const avgPrice = etsy?.pricing?.average || 'N/A';

    return `## 🎯 Executive Summary

### Key Metrics
| Metric | Value |
|--------|-------|
| Pinterest Trends Analyzed | ${trendCount} pins |
| Etsy Products Scanned | ${productCount} listings |
| Avg. Market Price | $${avgPrice} |
| Competitors Tracked | ${config.businesses.asobo.competitors.length} shops |

### Today's Highlights
${this.generateHighlights(data)}
`;
  }

  generateHighlights(data) {
    const highlights = [];
    
    if (data.etsy?.pricing) {
      const { recommendation } = data.etsy.pricing;
      highlights.push(`- 💰 **Pricing Insight:** ${recommendation}`);
    }

    if (data.pinterest) {
      const insights = data.pinterestInsights;
      if (insights?.popularStyles?.length) {
        highlights.push(`- 🎨 **Trending Style:** "${insights.popularStyles[0]}" is gaining traction`);
      }
      if (insights?.emergingThemes?.length) {
        highlights.push(`- 🌟 **Hot Theme:** "${insights.emergingThemes[0]}" searches up`);
      }
    }

    if (highlights.length === 0) {
      highlights.push('- 📈 Market stable - no major shifts detected');
    }

    return highlights.join('\n');
  }

  generateTrendingTopics(data) {
    if (!data.pinterest || data.pinterest.length === 0) {
      return `## 📌 Trending Topics\n\n_No trend data available today._`;
    }

    let md = `## 📌 Trending Topics\n\n`;

    data.pinterest.forEach(category => {
      md += `### ${category.category}\n\n`;
      
      if (category.trends.length > 0) {
        md += category.trends.slice(0, 5).map((trend, i) => {
          return `${i + 1}. ${trend.title}`;
        }).join('\n');
      } else {
        md += '_No trends found in this category_';
      }
      
      md += '\n\n';
    });

    // Add insights if available
    if (data.pinterestInsights) {
      const { popularStyles, trendingColors, emergingThemes } = data.pinterestInsights;
      
      md += `### 🎨 Style Insights\n\n`;
      
      if (popularStyles.length) {
        md += `**Popular Styles:** ${popularStyles.join(', ')}\n\n`;
      }
      if (trendingColors.length) {
        md += `**Trending Colors:** ${trendingColors.join(', ')}\n\n`;
      }
      if (emergingThemes.length) {
        md += `**Emerging Themes:** ${emergingThemes.join(', ')}\n\n`;
      }
    }

    return md;
  }

  generateCompetitorActivity(data) {
    if (!data.etsy?.competitors || data.etsy.competitors.length === 0) {
      return `## 🏪 Competitor Activity\n\n_No competitor data available._`;
    }

    let md = `## 🏪 Competitor Activity\n\n`;

    data.etsy.competitors.forEach(shop => {
      md += `### ${shop.name}\n`;
      md += `- Sales: ${shop.sales}\n`;
      md += `- Rating: ${shop.rating}\n`;
      md += `- Listings: ${shop.listingCount}\n\n`;
    });

    if (data.etsy?.products?.length > 0) {
      md += `### 📦 Top Performing Listings\n\n`;
      
      const topProducts = data.etsy.products
        .sort((a, b) => b.reviews - a.reviews)
        .slice(0, 5);

      topProducts.forEach((product, i) => {
        md += `${i + 1}. **${product.title}**\n`;
        md += `   - 💰 $${product.price} | ⭐ ${product.reviews} reviews | 🏪 ${product.shop}\n`;
        md += `   - [View on Etsy](${product.link})\n\n`;
      });
    }

    return md;
  }

  generateOpportunityAlerts(data) {
    const opportunities = this.identifyOpportunities(data);

    if (opportunities.length === 0) {
      return `## 🚨 Opportunity Alerts\n\n_No significant opportunities detected today._`;
    }

    let md = `## 🚨 Opportunity Alerts\n\n`;

    opportunities.forEach((opp, i) => {
      md += `### ${i + 1}. ${opp.title}\n`;
      md += `**Type:** ${opp.type} | **Priority:** ${opp.priority}\n\n`;
      md += `${opp.description}\n\n`;
      if (opp.action) {
        md += `**Suggested Action:** ${opp.action}\n\n`;
      }
    });

    return md;
  }

  identifyOpportunities(data) {
    const opportunities = [];

    // Price gap opportunity
    if (data.etsy?.pricing) {
      const avg = parseFloat(data.etsy.pricing.average);
      if (avg > 0 && avg < 5) {
        opportunities.push({
          title: 'Premium Pricing Gap',
          type: 'Pricing',
          priority: 'High',
          description: 'Average market price is low ($' + avg.toFixed(2) + '). Opportunity to position as premium quality.',
          action: 'Create premium bundle or add bonus pages to justify higher price point'
        });
      }
    }

    // Underserved niche detection
    if (data.pinterestInsights?.emergingThemes?.length > 0) {
      const theme = data.pinterestInsights.emergingThemes[0];
      opportunities.push({
        title: `Emerging Theme: "${theme}"`,
        type: 'Content',
        priority: 'Medium',
        description: `Pinterest shows growing interest in "${theme}" themes. Low competition detected.`,
        action: `Create 5-10 coloring pages featuring ${theme} style`
      });
    }

    return opportunities;
  }

  generateActionItems(data) {
    return `## ✅ Recommended Actions

### This Week's Priorities

1. **📊 Review Competitor Pricing**
   - Check if competitors changed prices
   - Consider testing new price point

2. **🎨 Create Content Based on Trends**
   - Review trending themes from Pinterest
   - Design 3-5 new pages aligned with trends

3. **📱 Update Product Descriptions**
   - Incorporate trending keywords
   - Refresh titles with current popular terms

4. **📈 Schedule Social Posts**
   - Pin trending designs to relevant boards
   - Cross-post to Instagram with trending hashtags

### Long-term Ideas

- [ ] Bundle complementary designs together
- [ ] Create themed collections (seasonal/holiday)
- [ ] Consider limited edition "trending now" mini-books
- [ ] Explore new niches identified in reports

---

*💙 Report generated with love by RITA*  
*🦋 Want different insights? Edit \`src/config.js\` to customize*  
*🤖 Running on autopilot at ${config.mode === 'production' ? 'PRODUCTION' : 'TEST'} mode*
`;
  }

  generateFooter() {
    return `---

**Data Sources:** Pinterest, Etsy  
**Update Frequency:** Daily at 06:00 UTC  
**Next Report:** Tomorrow morning

*Questions? Suggestions? Tell Earth to ping RITA!* 💬`;
  }

  /**
   * Get filename for today's report
   */
  getFilename() {
    return `report-${this.date}.md`;
  }
}

export default ReportGenerator;